class SearchPart
  include ActiveModel::Model

  attr_accessor :column1
  attr_accessor :column2
  attr_accessor :column3
  attr_accessor :column4
  attr_accessor :column5
  attr_accessor :column6
  attr_accessor :column7
  attr_accessor :column8
  attr_accessor :column9
  attr_accessor :column10
  attr_accessor :column11
  attr_accessor :column12
  attr_accessor :column13
  attr_accessor :column14
  attr_accessor :column15
  attr_accessor :column16
  attr_accessor :column17
  attr_accessor :column18
  attr_accessor :column19
  attr_accessor :column20
  attr_accessor :column21
  attr_accessor :column22
  attr_accessor :column23
  attr_accessor :column24
  attr_accessor :column25
  attr_accessor :column26
  attr_accessor :column27
  attr_accessor :column28
  attr_accessor :column29
  attr_accessor :column30
end
